// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "d03a1c61-d29e-4439-9ee4-02ba6a04207f");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1567522175);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1567522295);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1567523021);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1567521935);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1567521815);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1567522055);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1567522415);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 3375);
user_pref("browser.cache.disk.capacity", 788480);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contentblocking.introCount", 5);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1567459942);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{868d83a0-470c-429a-84aa-15144b368bb2}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1567523571661");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1567525355661");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1567522150503");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1567525750503");
user_pref("browser.search.region", "CA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190814054548");
user_pref("browser.slowStartup.averageTime", 3383);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20190814054548");
user_pref("browser.startup.homepage_override.mstone", "68.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1567522992);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1567459947064");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "1bf23f8464eb49bf9fe798360ae9988b");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Wed, 28 Aug 2019 19:55:12 GMT");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1567522175);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190814054548");
user_pref("extensions.lastAppVersion", "68.0.2");
user_pref("extensions.lastPlatformVersion", "68.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{72fc1999-a66e-4861-aa3b-b3a8d01b575f}\",\"addons\":{\"webcompat@mozilla.org\":{\"version\":\"5.0.2\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"dc261dcc-0268-43da-8685-9ff939116615\",\"fxmonitor@mozilla.org\":\"1f98e5dd-c1c9-4f40-bf1f-6922a629ef42\",\"screenshots@mozilla.org\":\"5c1ccd92-d5fd-445f-bdc7-d0993a376d61\",\"webcompat-reporter@mozilla.org\":\"06d1ccc4-9355-403d-879f-80588bf48c76\",\"webcompat@mozilla.org\":\"b64db036-bdcc-4403-82b3-cc6b360d1e6b\",\"default-theme@mozilla.org\":\"24161eac-edff-4fd2-9317-59de0d151682\",\"google@search.mozilla.org\":\"2e490702-db37-404a-8d1c-9c91af77591b\",\"amazon@search.mozilla.org\":\"bc7752be-f4ca-4011-a54b-accf4faae88a\",\"bing@search.mozilla.org\":\"349b7456-b3be-4c98-8ea1-c4e8515a4547\",\"ddg@search.mozilla.org\":\"607d97e0-9672-4dd8-a0f1-5763ac1e6627\",\"ebay@search.mozilla.org\":\"9b3b1662-f5a6-4672-a4b0-d9efa96072a4\",\"twitter@search.mozilla.org\":\"5d98cffa-4bd9-4d3a-af01-4db0f99d80dd\",\"wikipedia@search.mozilla.org\":\"4787261d-e41f-4fd8-bb81-6f0bcd9ed461\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1567518595);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190814054548");
user_pref("media.gmp-manager.lastCheck", 1567518594);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "7c624be8-ef44-402d-9612-508c1c6749ae");
user_pref("security.sandbox.plugin.tempDirSuffix", "334348c8-113b-4de3-bbe7-1b20de89080c");
user_pref("services.blocklist.pinning.checked", 1567522319);
user_pref("services.settings.clock_skew_seconds", -265);
user_pref("services.settings.last_etag", "\"1567468877808\"");
user_pref("services.settings.last_update_seconds", 1567522319);
user_pref("services.settings.main.cfr-fxa.last_check", 1567522319);
user_pref("services.settings.main.cfr.last_check", 1567522319);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1567522319);
user_pref("services.settings.main.hijack-blocklists.last_check", 1567522319);
user_pref("services.settings.main.language-dictionaries.last_check", 1567522319);
user_pref("services.settings.main.normandy-recipes.last_check", 1567522319);
user_pref("services.settings.main.sites-classification.last_check", 1567522319);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1567522319);
user_pref("services.settings.security.onecrl.checked", 1567522319);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1567522990);
user_pref("toolkit.telemetry.cachedClientID", "e2e93611-1785-434e-b40e-ba7c32b76a6a");
user_pref("toolkit.telemetry.previousBuildID", "20190814054548");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
